In [1]:
import numpy as np

## Empty Array

In [2]:
# If you provide equal values for start and stop, then you’ll get an empty array:
emp_arr = np.arange(2, 2)
emp_arr

array([], dtype=int32)

In [3]:
#One of the unusual cases is when start is greater than stop and step is positive, or when start is less than stop and step is negative:

empty= np.arange(8, 2, 1)
empty

array([], dtype=int32)

In [4]:
empty = np.arange(2, 8, -1)
empty

array([], dtype=int32)

## Providing Neg Argument

In [5]:
np.arange(-5, -1)

array([-5, -4, -3, -2])

In [6]:
np.arange(-8, -2, 2)

array([-8, -6, -4])

In [7]:
np.arange(-5, 6, 4)

array([-5, -1,  3])

## Counting Backwards

In [8]:
np.arange(5, 1, -1)

array([5, 4, 3, 2])

In [9]:
np.arange(7, 0, -3)

array([7, 4, 1])

In [10]:
np.arange(1, 8, 3)[::-1]

array([7, 4, 1])

In [11]:
np.flip(np.arange(1, 8, 3))

array([7, 4, 1])

## NumPy Indexing and Selection

In [12]:
#Creating sample array
arr = np.arange(0,11)

In [13]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection

In [14]:
#Get a value at an index
arr[8]

8

In [15]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [16]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [17]:
#Setting a value with index range (Broadcasting)
arr = np.arange(0,11)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
#Change Slice - slice_of_arr = [0, 1, 2, 3, 4, 5]
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. Comma notation is recommended.

In [23]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [25]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [26]:
# Getting individual element value
arr_2d[1,0]

20

In [27]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [28]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [29]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## More Indexing Help
Indexing a 2D matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching *NumPy indexing* to find useful images, like this one:

<img src= 'numpy_indexing.png' width=500/> Image source: http://www.scipy-lectures.org/intro/numpy/numpy.html

In [30]:
new_arr = np.arange(0,56)
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

In [31]:
# Convert this numpy 1D array into 2D numpy array
reshaped_2D = new_arr.reshape(7,8)
reshaped_2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [32]:
reshaped_2D[2, 4:6]

array([20, 21])

In [33]:
reshaped_2D[:, 4:8]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [36, 37, 38, 39],
       [44, 45, 46, 47],
       [52, 53, 54, 55]])

In [34]:
reshaped_2D[4:, 4:]

array([[36, 37, 38, 39],
       [44, 45, 46, 47],
       [52, 53, 54, 55]])

In [35]:
# 2::3 - starts from 2nd row and takes every 3rd row downwards
reshaped_2D[2::3]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [36]:
reshaped_2D[2::2]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [37]:
reshaped_2D[2::2, 2::2]

array([[18, 20, 22],
       [34, 36, 38],
       [50, 52, 54]])

## Conditional Selection

In [38]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [40]:
bool_arr = arr>4

In [41]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])