In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [3]:
type(my_list)

list

## Creating NumPy Arrays from Objects

### From a Python List

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods to create arrays

### arange

Return evenly spaced values within a given interval.

In [8]:
# [start,] stop[, step
np.arange(0,10) 

<function numpy.arange>

In [43]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [44]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### zeros and ones

Generate arrays of zeros or ones.

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Return evenly spaced numbers over a specified interval. np.linspace(start,stop,num=50)


In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Note that `.linspace()` *includes* the stop value. To obtain an array of common fractions, increase the number of items:</font>

In [16]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

Creates an identity matrix

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 
Numpy also has lots of ways to create random number arrays:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. 
The dimensions of the returned array, must be non-negative

In [18]:
# coloumn

np.random.rand(2)

array([0.36055858, 0.29036225])

In [54]:
# row, column
np.random.rand(4,3)

array([[0.12261922, 0.29611713, 0.88643606],
       [0.30204887, 0.71395542, 0.61204708],
       [0.42718116, 0.23902564, 0.3690147 ],
       [0.59210721, 0.35075321, 0.21489643]])

In [55]:
# no of sets, row, column
np.random.rand(6,4,3)

array([[[1.16462749e-01, 8.79766938e-01, 4.40312976e-01],
        [6.25208322e-01, 4.90410361e-01, 8.72566518e-01],
        [5.46934852e-01, 4.80781418e-01, 9.24600990e-01],
        [7.19689596e-01, 1.11549907e-01, 1.77704461e-01]],

       [[7.87122863e-01, 8.35851321e-01, 5.45190829e-01],
        [5.54455228e-01, 6.31932963e-01, 4.39115774e-01],
        [6.80199123e-01, 1.08481258e-01, 9.61279242e-01],
        [7.50154824e-01, 6.31174204e-01, 3.16322057e-01]],

       [[1.60955487e-01, 4.09342964e-01, 6.61576741e-01],
        [6.33709743e-01, 3.82641155e-01, 6.13286394e-01],
        [8.13748296e-01, 2.62847723e-02, 4.50621048e-01],
        [7.58555228e-01, 5.46144470e-01, 6.51476088e-01]],

       [[5.16676393e-01, 9.91874545e-01, 5.46215365e-02],
        [4.91044822e-01, 9.14165491e-02, 1.59785562e-01],
        [3.83038350e-01, 1.55540092e-01, 9.63687166e-01],
        [9.46789777e-01, 3.36109646e-01, 6.39747712e-01]],

       [[5.33753321e-01, 8.15586981e-01, 6.27445610e-01],
      

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear.

In [20]:
np.random.randn(2)

array([2.24865358, 0.8179477 ])

In [56]:
np.random.randn(6,5)

array([[ 2.00015251,  0.5154577 , -0.45346265,  1.14706865, -0.24286282],
       [ 0.25120945, -1.3363713 , -1.50866377,  0.55365553,  1.10372895],
       [ 1.9456675 , -0.80937244,  1.46374412,  1.3144469 , -0.49116286],
       [ 1.38808689,  0.94421638,  1.14218308,  2.16736038,  1.10066185],
       [-2.13689813,  0.3225605 , -1.5668015 ,  0.15145007,  0.09362786],
       [-0.5836949 , -1.02760314, -0.5303319 , -0.33716055, -0.13170485]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).

In [60]:
# any integer between d1, d2
np.random.randint(90,100)

97

In [61]:
np.random.randint(10,50, size=(4,4))

array([[26, 47, 45, 45],
       [28, 11, 26, 39],
       [19, 44, 45, 42],
       [10, 27, 13, 36]])

In [63]:
# d1, d2 range, d3= no of data
np.random.randint(1,100,13)

array([16, 81, 55, 61, 95, 79, 77, 40, 91, 21, 66,  8, 71])

In [66]:
names = ['Alice', 'Bob', 'Tommy', 'Grace']
np.random.choice(names)

'Grace'

### random_samples 

In [68]:
# Return random floats in the half-open interval [0.0, 1.0).
np.random.random_sample()

0.5173819588480452

In [69]:
type(np.random.random_sample())

float

In [70]:
# 5 random values
np.random.random_sample((5,))

array([0.76455663, 0.83542796, 0.61942155, 0.74872364, 0.522706  ])

In [71]:
# Three-by-two array of random numbers from [-5, 0):

5 * np.random.random_sample((3, 2)) - 5

array([[-1.90823311, -3.02714151],
       [-1.04062867, -2.65864535],
       [-1.59893548, -1.89285311]])

### log

In [72]:
# Samples are drawn from a logarithmic series distribution with specified shape parameter, 0 < ``p`` < 1.
a = .6
s = np.random.logseries(a, 10)
s

array([1, 1, 2, 2, 1, 3, 2, 1, 3, 2])

In [77]:
# Draw samples from a logistic distribution.
loc, scale = 10, 1
s = np.random.logistic(loc, scale, 10)
s

array([ 7.74953501,  8.65732102, 14.80753603,  9.32624992,  9.07549455,
        7.62702825, 10.82285842, 10.03301654,  8.32343517, 10.54467054])

In [80]:
# Draw samples from a log-normal distribution with specified mean,standard deviation, and array shape.  Note that the mean and standard
# deviation are not the values for the distribution itself, but of the underlying normal distribution it is derived from.
mu, sigma = 3., 1. # mean and standard deviation
s = np.random.lognormal(mu, sigma, 15)
s

array([ 17.51350578,  22.06139092,  12.93231587,  50.5286791 ,
        76.02947528,  43.18275234,  18.17379995,  13.4246693 ,
        59.29086634,  27.76574284,  35.0393212 ,  27.27327653,
         9.55479276,  95.90800084, 233.63648419])

### mean, median

In [81]:
arr = np.array([1, 2, 3])
mean_value = np.mean(arr)
print(mean_value)

2.0


In [85]:
# middle number; found by ordering all data points
arr = np.array([5, 2, 3, 6])
median_value = np.median(arr)
print(median_value)
# (3+5)/2 = 4

4.0


### seed
Can be used to set the random state, so that the same "random" results can be reproduced.

In [47]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [46]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## Reshape
Returns an array containing the same data with a new shape.

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [30]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [31]:
ranarr.max()

39

In [32]:
ranarr.argmax()

7

In [33]:
ranarr.min()

2

In [34]:
ranarr.argmin()

9

## Shape

Shape is an attribute that arrays have (not a method)

In [35]:
# Vector - (25,) this means the array has only 25 numbers.
arr.shape

(25,)

In [36]:
# Notice the two sets of brackets - 1 row, 25 cols
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
# 25 rows, 1 col
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array

In [40]:
arr.dtype

dtype('int32')

In [41]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')